# Service
apiVersion: v1
kind: Service
metadata:
  name: composetoolbox
  namespace: tools
spec:
  type: ClusterIP
  selector:
    app: composetoolbox
  ports:
    - name: http
      port: 3000
      targetPort: 3000
