apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: booklore
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`books.smeyer.ca`)
      kind: Rule
      services:
        - name: booklore
          port: 80
          scheme: http
   tls:
    secretName: smeyer-wildcard-tls
