apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: booklore
resources:
  - namespace.yaml
  - mariadb-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - books-pv.yaml
  - books-pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
