kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: skooner
  namespace: skooner
spec:
  rules:
  -
    host: skooner.smeyer.ca
    http:
      paths:
      -
        path: /
        backend:
          serviceName: skooner
          servicePort: 80
