apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: skooner
  namespace: skooner
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`skooner.smeyer.ca`)
      kind: Rule
      services:
        - name: skooner
          port: 80
