---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
      
- Apps:
    - GitHub Blog:
        icon: github-light.png
        href: https://smeyer.ca/
        description: my blog
    - Wikijs:
        icon: wikijs-alt.png
        href: https://wiki.smeyer.ca/
        description: my wiki
    - Immich:
        icon: immich.png
        href: https://pics.smeyer.ca/
        description: photo curation
    - Drawio:
        icon: draw-io.png
        href: https://drawio.smeyer.ca/
        description: Drawing tool
    - IT-Tools:
        icon: it-tools.png
        href: https://tools.smeyer.ca/
        description: Handy IT tools

    - Compose Tool Box:
        icon: docker-compose.webp
        href: https://compose.smeyer.ca
        description: compose file review tool
    - PDFding:
        icon: pdfding-light.png
        href: https://pdf.smeyer.ca
        description: pdf editing tool 
    - Giftful:
        icon: https://dyr69yan0mo6n.cloudfront.net/giftful/images/logo_giftful.png?v=1
        href: https://giftful.com/stevenmeyer2
        description: gift registry of things that I covet


        
- Host:
    - ZimaOS:
        icon: zima-os.png
        href: http://10.0.0.10
        description: Nas host with docker store
    - PiHole:
        icon: pi-hole.png
        href: http://10.0.0.10:8080/admin/
        description: dns management
        
    - Nginx Proxy Manager:
        icon: npm.png
        href: http://proxy.smeyer.ca/
        description: proxy management 
  
    - Portainer:
        icon: portainer-alt.png
        href: https://portainer.smeyer.ca/
        description: k3s/docker management


- Infra:
    - Unifi Gateway:
       icon: ubiquiti-unifi.png
       href: https://unifi.smeyer.ca
       description: unifi
       
    - Traefik Dashboard:
        icon: traefik.png
        href: https://traefik.smeyer.ca/dashboard/#/
        description: k3s reverse proxy 
        
    - HomeAssistant:
        icon: home-assistant.png
        href: http://home.smeyer.ca/
        description: home automation
    - Argo-CD:
        icon: argo-cd.png
        href: https://argo.smeyer.ca/
        description: dns management 
    - Proxmox:
        icon: proxmox.png
        href: https://pve2.smeyer.ca/
        description: proxmox host

    - Longhorn:
       icon: longhorn.png
       href: https://longhorn.smeyer.ca
       description: storage

    - Adminer:
       icon: adminer.png
       href: http://10.0.0.10:8082
       description: database management interface
       
       



- Media: 
    - Plex:
        icon: plex.png
        href: http://plex.smeyer.ca/
        description: Media Viewer
        
    - Sonarr:
        icon: sonarr.png
        href: https://tv.smeyer.ca/
        description: Tv management
        namespace: media

    - Radarr:
        icon: radarr.png
        href: https://movies.smeyer.ca/
        description: Movies management
    - Lidarr:
        icon: lidarr.png
        href: https://music.smeyer.ca/
        description: Music management

    - Kavita:
        icon: kavita.png
        href: https://books.smeyer.ca/
        description: Book reader

    - LazyLibrarian:
        icon: lazylibrarian.png
        href: https://library.smeyer.ca
        description: books management
        
    - Transmission-vpn:
        icon: transmission.png
        href: https://transmission.smeyer.ca/
        description: Downloader

    - Prowlarr:
        icon: prowlarr.png
        href: https://index.smeyer.ca/
        description: index management




   
