---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
      
- Apps:
    - HomeAssistant:
        icon: home-assistant.png
        href: http://10.0.2.4:8123/
        description: home automation   
    
    - GitHub Blog:
        icon: github-light.png
        href: https://smeyer.ca/
        description: my blog
    - Ghost:
        icon: ghost.png
        href: https://ghost.smeyer.ca/
        description: my nicer, newer blog
    - Immich:
        icon: immich.png
        href: https://pics.smeyer.ca/
        description: photo curation
    - Drawio:
        icon: draw-io.png
        href: https://drawio.smeyer.ca/
        description: Drawing tool
    - IT-Tools:
        icon: it-tools.png
        href: https://tools.smeyer.ca/
        description: Handy IT tools

    - Compose Tool Box:
        icon: docker-moby.png
        href: https://compose.smeyer.ca
        description: compose file review tool
    - PDFding:
        icon: pdfding-light.png
        href: https://pdf.smeyer.ca
        description: pdf editing tool 

    - Adminer:
       icon: adminer.png
       href: http://db.smeyer.ca
       description: database management interface
       
    - Giftful:
        icon: https://dyr69yan0mo6n.cloudfront.net/giftful/images/logo_giftful.png?v=1
        href: https://giftful.com/stevenmeyer2
        description: gift registry of things that I covet


        
- Host:
    - Monitor:
        icon: pulse.png
        href: http://monitor.smeyer.ca
        description: Monitoring plex

        
    - Traefik Dashboard:
        icon: traefik.png
        href: https://traefik.smeyer.ca/dashboard/#/
        description: k3s reverse proxy
    - Argo-CD:
        icon: argo-cd.png
        href: https://argo.smeyer.ca/
        description: dns management 
    - Longhorn:
       icon: longhorn.png
       href: http://longhorn.smeyer.ca
       description: storage

    - Portainer:
        icon: portainer-alt.png
        href: https://portainer.smeyer.ca/
        description: k3s/docker management
- Infra:
    - Unifi Gateway:
       icon: ubiquiti-unifi.png
       href: https://unifi.smeyer.ca
       description: unifi
       
    - PiHole:
        icon: pi-hole.png
        href: http://pihole.smeyer.ca/
        description: dns management
        
    - Nginx Proxy Manager:
        icon: npm.png
        href: https://proxy.smeyer.ca/
        description: proxy management      

    - Proxmox:
        icon: proxmox.png
        href: https://pve.smeyer.ca/
        description: proxmox host
    - Proxmox Backup Server:
        icon: pbs.png
        href: https://pbs.smeyer.ca/
        description: proxmox backup host

- Media: 
    - Plex:
        icon: plex.png
        href: http://plex.smeyer.ca/
        description: Media Viewer
        
    - Sonarr:
        icon: sonarr.png
        href: https://tv.smeyer.ca/
        description: Tv management
        namespace: media

    - Radarr:
        icon: radarr.png
        href: https://movies.smeyer.ca/
        description: Movies management
    - Lidarr:
        icon: lidarr.png
        href: https://music.smeyer.ca/
        description: Music management

    - Kavita:
        icon: kavita.png
        href: https://books.smeyer.ca/
        description: Book reader

    - LazyLibrarian:
        icon: lazylibrarian.png
        href: https://library.smeyer.ca
        description: books management
        
    - Transmission-vpn:
        icon: transmission.png
        href: https://transmission.smeyer.ca/
        description: Downloader

    - Prowlarr:
        icon: prowlarr.png
        href: https://index.smeyer.ca/
        description: index management
