---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
backgroundOpacity: 0.6
cardBlur: md # or sm, lg
headerStyle: underlined # or boxed, boxedWidgets, clean
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
title: Bobo Homepage
statusStyle: "dot"
hideVersion: false
disableUpdateCheck: false
useEqualHeights: true
layout:

  Apps:
    columns: 5
    style: row
    icon: mdi-folder-multiple-image
  Media:
    columns: 5
    style: row
    icon: mdi-folder-multiple-image
  Host:
    columns: 5
    style: row
    icon: mdi-folder-multiple-image
  Infra: 
    column: 5
    style: row
    icon: mdi-folder-multiple-image
