# wikijs-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      initContainers:
       - name: fix-permissions
         image: busybox
         command: ['sh', '-c', 'chown -R 1000:1000 /wiki/data || true']
         volumeMounts:
           - name: wikijs-data
             mountPath: /wiki/data
      containers:
        - name: wikijs
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wikijs-db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: wikijs-db-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wikijs-db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wikijs-db-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wikijs-db-secret
                  key: DB_NAME
            - name: TZ
              value: America/Vancouver
          volumeMounts:
            - name: wikijs-data
              mountPath: /wiki/data
      volumes:
        - name: wikijs-data
          persistentVolumeClaim:
            claimName: wikijs-data
