apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - machinelearning.yaml
  - redis.yaml
  - server-service.yaml
