apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml
  - machinelearning.yaml
  - redis.yaml
  - server-services.yaml
