apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: https://ghost.smeyer.ca
            - name: mail__transport
              value: SMTP
            - name: mail__options__service
              value: Mailgun
            - name: mail__options__host
              value: smtp.mailgun.org
            - name: mail__options__port
              value: "587"
            - name: mail--options--secure
              value: "false"
            - name: mail__options__auth__user
              value: postmaster@mg.smeyer.ca
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: ghost-mailgun           
                  key: mailgun-password
            - name: mail__from
              value: "no-reply@smeyer.ca"
            - name: database__client
              value: mysql
          envFrom:
            - secretRef:
                name: ghost-db-secret
          volumeMounts:
            - name: ghost
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost
          persistentVolumeClaim:
            claimName: ghost
