    # Middleware: redirect HTTP -> HTTPS
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: portainer-redirect-https
  namespace: portainer
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.smeyer.ca`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    certResolver: letsencrypt
---
# IngressRoute for HTTP (only used for redirect)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-http
  namespace: portainer
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`portainer.smeyer.ca`)
      kind: Rule
      middlewares:
        - name: portainer-redirect-https
      services:
        - name: portainer
          port: 80
